language: python
matrix:
  include:
   - python: 2.7
     env: TOXENV=py27-django15
   - python: 2.7
     env: TOXENV=py27-django16
   - python: 2.7
     env: TOXENV=py27-django17
   - python: 2.7
     env: TOXENV=py27-django18
   - python: 2.7
     env: TOXENV=py27-django19
   - python: 2.7
     env: TOXENV=py27-django110
   - python: 2.7
     env: TOXENV=py27-django111
   - python: pypy
     env: TOXENV=pypy-django15
   - python: pypy
     env: TOXENV=pypy-django16
   - python: pypy
     env: TOXENV=pypy-django17
   - python: pypy
     env: TOXENV=pypy-django18
   - python: pypy
     env: TOXENV=pypy-django19
   - python: pypy
     env: TOXENV=pypy-django110
   - python: pypy
     env: TOXENV=pypy-django111
   - python: 3.3
     env: TOXENV=py33-django17
   - python: 3.3
     env: TOXENV=py33-django18
   # - python: 3.3
   #   env: TOXENV=py33-django1.9 this version does not support py33.
   - python: 3.4
     env: TOXENV=py34-django17
   - python: 3.4
     env: TOXENV=py34-django18
   - python: 3.4
     env: TOXENV=py34-django19
   - python: 3.4
     env: TOXENV=py34-django110
   - python: 3.4
     env: TOXENV=py34-django111
   - python: 3.4
     env: TOXENV=py34-django20
   # - python: 3.5
   #   env: TOXENV=py35-django1.7 do not use this combination. 
   #   see also http://stackoverflow.com/q/34827566
   - python: 3.5
     env: TOXENV=py35-django18
   - python: 3.5
     env: TOXENV=py35-django19
   - python: 3.5
     env: TOXENV=py35-django110
   - python: 3.5
     env: TOXENV=py35-django111
   - python: 3.5
     env: TOXENV=py35-django20
   - python: 3.6
     env: TOXENV=py36-django18
   - python: 3.6
     env: TOXENV=py36-django19
   - python: 3.6
     env: TOXENV=py36-django110
   - python: 3.6
     env: TOXENV=py36-django111
   - python: 3.6
     env: TOXENV=py36-django20
   - python: 3.6
     env: TOXENV=py36-django21
   - python: 3.6
     env: TOXENV=py36-django22
   - python: 3.7
     env: TOXENV=py37-django20
   - python: 3.7
     env: TOXENV=py37-django21
   - python: 3.7
     env: TOXENV=py37-django22
   - python: 3.6
     env: TOXENV=flake8

install:
  - pip install tox
  - if test "$TOXENV" = py36-django111; then pip install coveralls ; fi
script: tox
after_script:
  - if test "$TOXENV" = py36-django111; then coveralls ; fi
